//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("demo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha de comunicação ao acessar serviços núcleo do barramento..
        /// </summary>
        internal static string BusCommFailureErrorMsg {
            get {
                return ResourceManager.GetString("BusCommFailureErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha no barramento. Causa:.
        /// </summary>
        internal static string BusServiceFailureErrorMsg {
            get {
                return ResourceManager.GetString("BusServiceFailureErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O barramento está inacessível..
        /// </summary>
        internal static string BusTransientErrorMsg {
            get {
                return ResourceManager.GetString("BusTransientErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar realizar o login por senha no barramento: a senha fornecida não foi validada para a entidade .
        /// </summary>
        internal static string ClientAccessDenied {
            get {
                return ResourceManager.GetString("ClientAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fim..
        /// </summary>
        internal static string ClientOK {
            get {
                return ResourceManager.GetString("ClientOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A faceta encontrada na oferta não implementa a interface esperada..
        /// </summary>
        internal static string FacetFoundWrongType {
            get {
                return ResourceManager.GetString("FacetFoundWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível encontrar uma faceta da interface esperada na oferta..
        /// </summary>
        internal static string FacetNotFoundInOffer {
            get {
                return ResourceManager.GetString("FacetNotFoundInOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A integração do serviço sendo utilizado com o barramento está incorreta..
        /// </summary>
        internal static string InvalidRemoteCodeErrorMsg {
            get {
                return ResourceManager.GetString("InvalidRemoteCodeErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar realizar o login por certificado no barramento: o barramento não tem certificado registrado para a entidade .
        /// </summary>
        internal static string MissingCertificateForEntity {
            get {
                return ResourceManager.GetString("MissingCertificateForEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há um login válido no momento para a entidade utilizada..
        /// </summary>
        internal static string NoLoginCodeErrorMsg {
            get {
                return ResourceManager.GetString("NoLoginCodeErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foi encontrada uma oferta com um serviço funcional..
        /// </summary>
        internal static string OfferFound {
            get {
                return ResourceManager.GetString("OfferFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrada uma oferta com um serviço funcional..
        /// </summary>
        internal static string OfferFunctionalNotFound {
            get {
                return ResourceManager.GetString("OfferFunctionalNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressione qualquer tecla para sair..
        /// </summary>
        internal static string PressAnyKeyToExit {
            get {
                return ResourceManager.GetString("PressAnyKeyToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta removida do barramento..
        /// </summary>
        internal static string RemovedOffer {
            get {
                return ResourceManager.GetString("RemovedOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removendo oferta do barramento antes de terminar o processo....
        /// </summary>
        internal static string RemovingOffer {
            get {
                return ResourceManager.GetString("RemovingOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar realizar o login por certificado no barramento: a chave privada fornecida não é a esperada..
        /// </summary>
        internal static string ServerAccessDenied {
            get {
                return ResourceManager.GetString("ServerAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servidor no ar..
        /// </summary>
        internal static string ServerOK {
            get {
                return ResourceManager.GetString("ServerOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha de comunicação ao acessar o serviço..
        /// </summary>
        internal static string ServiceCommFailureErrorMsg {
            get {
                return ResourceManager.GetString("ServiceCommFailureErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe mais de um serviço no barramento. Tentaremos encontrar um funcional..
        /// </summary>
        internal static string ServiceFoundMoreThanExpected {
            get {
                return ResourceManager.GetString("ServiceFoundMoreThanExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testando uma das ofertas recebidas....
        /// </summary>
        internal static string ServiceFoundTesting {
            get {
                return ResourceManager.GetString("ServiceFoundTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O serviço não se encontra no barramento..
        /// </summary>
        internal static string ServiceNotFound {
            get {
                return ResourceManager.GetString("ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O serviço está inacessível..
        /// </summary>
        internal static string ServiceTransientErrorMsg {
            get {
                return ResourceManager.GetString("ServiceTransientErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar registrar a oferta no barramento: O componente que implementa o serviço apresenta facetas com interfaces que não estão autorizadas para a entidade realizando o registro da oferta de serviço..
        /// </summary>
        internal static string UnauthorizedFacets {
            get {
                return ResourceManager.GetString("UnauthorizedFacets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar remover a oferta do barramento: operação não autorizada. O login utilizado para remover a oferta não é o mesmo que a registrou e não é um administrador do barramento..
        /// </summary>
        internal static string UnauthorizedRemoveOffer {
            get {
                return ResourceManager.GetString("UnauthorizedRemoveOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O serviço sendo utilizado não está mais autenticado no barramento..
        /// </summary>
        internal static string UnknownBusCodeErrorMsg {
            get {
                return ResourceManager.GetString("UnknownBusCodeErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O serviço sendo utilizado não foi capaz de validar a chamada..
        /// </summary>
        internal static string UnverifiedLoginCodeErrorMsg {
            get {
                return ResourceManager.GetString("UnverifiedLoginCodeErrorMsg", resourceCulture);
            }
        }
    }
}
