#ifndef OPEN_BASICS_IDL
#define OPEN_BASICS_IDL


/* OpenBus Basics */
module openbusidl {
module basic_types {

	/* --- Definitions --- */
	/** \brief Representa o nome de um metadado. */
	typedef string MetadataName;
	/** \brief Representa o valor de um metadado. */
	typedef any MetadataValue;

	/** \brief Representa  o tempo em millisegundos desde de 1 de janeiro de 1970. */
	typedef long long TimeStamp;


	/* --- Structs --- */
	/** \brief Representa um metadado. */
	struct Metadata {
		MetadataName name;
		MetadataValue value;
	};
	typedef sequence<Metadata> MetadataList;

};
};

#endif
